'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight, Bookmark, Check, ChevronRight, CircleHelp, Globe2, Layers3, Radio, RefreshCw, Search, ShieldCheck, SlidersHorizontal, Sparkles, X, Zap, BarChart3, Cpu, Leaf, Menu, ExternalLink, Sun, Moon, HardDrive, Download, Upload, MapPin} from 'lucide-react';
import {categories, categoryNames, context} from '@/lib/content';
import type {Article,Category,NewsData,Region} from '@/lib/types';
import {regions,regionNames} from '@/lib/regions.mjs';
import {loadCache,mergeNews,persistCache,validArticle,validData} from '@/lib/storage.mjs';
import WorldMap from './world-map';
import Activity from './activity';
import FocusFilter from './focus-filter';
import {focusEvidence,focusTopics,matchesFocus} from '@/lib/focus.mjs';
type Language='th'|'en'; type View='feed'|'saved'|'sources'|'about'|'storage';
const icons={world:Globe2,economy:BarChart3,technology:Cpu,energy:Zap,climate:Leaf};
export default function Dashboard(){
 const [focus,setFocus]=useState('all');
 const [lang,setLang]=useState<Language>('th'); const [view,setView]=useState<View>('feed'); const [category,setCategory]=useState<Category|'all'>('all'); const [region,setRegion]=useState<Region|'all'>('all'); const [query,setQuery]=useState(''); const [sort,setSort]=useState('newest'); const [sourceFilter,setSourceFilter]=useState('all'); const [data,setData]=useState<NewsData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const [saved,setSaved]=useState<Article[]>([]); const [storageError,setStorageError]=useState(false); const [active,setActive]=useState<Article|null>(null); const [mobile,setMobile]=useState(false); const [limit,setLimit]=useState(24); const [theme,setTheme]=useState<'dark'|'light'>('dark'); const [hydrated,setHydrated]=useState(false); const [cached,setCached]=useState(false); const [message,setMessage]=useState(''); const [now,setNow]=useState(0); const dialog=useRef<HTMLDialogElement>(null); const importInput=useRef<HTMLInputElement>(null); const inFlight=useRef(false);
 const t=(th:string,en:string)=>lang==='th'?th:en;
 const refresh=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;setLoading(true);try{const r=await fetch('/api/news',{signal:AbortSignal.timeout(25000)});const json=validData(await r.json()) as NewsData|null;if(!json)throw new Error('Invalid response');if(r.ok){setData(old=>mergeNews(json,old) as NewsData);setError(false);setCached(false);setNow(Date.now());}else{setData(old=>old?{...old,sources:json.sources}:json);setError(true);}}catch{setError(true);}finally{setLoading(false);inFlight.current=false;}},[]);
 useEffect(()=>{
  setNow(Date.now());
  try{
   const old=loadCache(localStorage) as NewsData|null;if(old){setData(old);setCached(true);}
   const raw=JSON.parse(localStorage.getItem('nowinfo:saved')||'[]');if(Array.isArray(raw))setSaved(raw.map(validArticle).filter(Boolean).slice(0,100) as Article[]);
   const l=localStorage.getItem('nowinfo:language');if(l==='en')setLang('en');
   const mode=localStorage.getItem('nowinfo:theme');if(mode==='light')setTheme('light');
   const prefs=JSON.parse(localStorage.getItem('nowinfo:filters:v2')||'{}');if(['all','relevant',...focusTopics.map(t=>t.id)].includes(prefs.focus))setFocus(prefs.focus);if(categories.includes(prefs.category)||prefs.category==='all')setCategory(prefs.category);if(regions.includes(prefs.region)||prefs.region==='all')setRegion(prefs.region);if(['newest','oldest'].includes(prefs.sort))setSort(prefs.sort);if(typeof prefs.source==='string')setSourceFilter(prefs.source);
  }catch{setStorageError(true);}
  setHydrated(true);refresh();const id=setInterval(()=>{if(document.visibilityState==='visible')refresh();},300000);return()=>clearInterval(id);
 },[refresh]);
 useEffect(()=>{if(!hydrated)return;document.documentElement.lang=lang;document.documentElement.dataset.theme=theme;try{localStorage.setItem('nowinfo:language',lang);localStorage.setItem('nowinfo:theme',theme);localStorage.setItem('nowinfo:filters:v2',JSON.stringify({category,region,sort,source:sourceFilter,focus}));}catch{setStorageError(true);}},[hydrated,lang,theme,category,region,sort,sourceFilter,focus]);
 useEffect(()=>{if(!hydrated||!data)return;try{if(!persistCache(localStorage,data))setStorageError(true);}catch{setStorageError(true);}},[hydrated,data]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem('nowinfo:saved',JSON.stringify(saved));}catch{setStorageError(true);}},[hydrated,saved]);
 useEffect(()=>{if(active&&!dialog.current?.open)dialog.current?.showModal();},[active]);
 useEffect(()=>{setLimit(24);},[view,category,region,query,sort,sourceFilter,focus]);
 function bookmark(article:Article){setSaved(previous=>previous.some(a=>a.id===article.id||a.url===article.url)?previous.filter(a=>a.id!==article.id&&a.url!==article.url):[article,...previous].slice(0,100));}
 function navigate(v:View){setFocus('all');setView(v);setMobile(false);setQuery('');setCategory('all');setRegion('all');setSourceFilter('all');}
 function selectCategory(c:Category|'all'){setCategory(c);setView('feed');setMobile(false);}
 function exportData(){const file=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),data,saved,preferences:{lang,theme}},null,2)],{type:'application/json'});const url=URL.createObjectURL(file);const link=document.createElement('a');link.href=url;link.download='nowinfo-backup.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importData(file?:File){if(!file)return;try{if(file.size>2000000)throw new Error();const input=JSON.parse(await file.text());if(input.version!==2||!Array.isArray(input.saved)||input.saved.length>100)throw new Error();const imported=validData(input.data) as NewsData|null;if(input.data&&!imported)throw new Error();const bookmarks=input.saved.map(validArticle);if(bookmarks.some((a:Article|null)=>!a))throw new Error();if(imported)setData(old=>mergeNews(old||imported,imported) as NewsData);setSaved(old=>[...old,...bookmarks].filter((a,i,list)=>list.findIndex(b=>b.id===a.id||b.url===a.url)===i).slice(0,100));if(['th','en'].includes(input.preferences?.lang))setLang(input.preferences.lang);if(['dark','light'].includes(input.preferences?.theme))setTheme(input.preferences.theme);setMessage(t('นำเข้าข้อมูลแล้ว รวมกับข่าวและรายการบันทึกเดิม','Backup imported and merged with your existing stories.'));}catch{setMessage(t('นำเข้าไม่ได้ กรุณาใช้ไฟล์สำรอง NowInfo ที่ถูกต้อง ขนาดไม่เกิน 2 MB','Import failed. Use a valid NowInfo backup under 2 MB.'));}finally{if(importInput.current)importInput.current.value='';}}
 const filtered=useMemo(()=>{const list=view==='saved'?saved:data?.articles||[];return list.filter(a=>matchesFocus(a,focus)&&(category==='all'||a.category===category)&&(sourceFilter==='all'||a.source===sourceFilter)&&(region==='all'||a.regions.includes(region))&&`${a.title} ${a.source} ${categoryNames.th[a.category]} ${categoryNames.en[a.category]}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='oldest'?(Date.parse(a.publishedAt||'')||0)-(Date.parse(b.publishedAt||'')||0):(Date.parse(b.publishedAt||'')||0)-(Date.parse(a.publishedAt||'')||0));},[view,saved,data,category,region,sourceFilter,query,sort,focus]);
 const sourceCount=data?.sources.filter(s=>s.status==='ok').length||0;const publishers=[...new Set((view==='saved'?saved:data?.articles||[]).map(a=>a.source))];
 const date=(value:string|null)=>value&&Number.isFinite(Date.parse(value))?new Intl.DateTimeFormat(lang==='th'?'th-TH':'en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Bangkok'}).format(new Date(value)):t('ไม่ระบุเวลา','Time unavailable');
 const isSaved=(a:Article)=>saved.some(s=>s.id===a.id||s.url===a.url);
 const clearFilters=()=>{setFocus('all');setQuery('');setCategory('all');setRegion('all');setSourceFilter('all');};
 const title=view==='storage'?t('ข้อมูลบนอุปกรณ์','Your local workspace'):view==='saved'?t('ข่าวที่บันทึกไว้','Your reading list'):view==='sources'?t('แหล่งข้อมูล','Source directory'):view==='about'?t('เบื้องหลังข้อมูล','Behind the feed'):t('จับตาโลกในภาพเดียว','The world. In one view.');
 const nav=[{id:'feed' as View,icon:Layers3,label:t('ภาพรวมข่าว','Overview')},{id:'saved' as View,icon:Bookmark,label:t('บันทึกไว้อ่าน','Saved stories')},{id:'sources' as View,icon:Radio,label:t('แหล่งข้อมูล','Sources')},{id:'storage' as View,icon:HardDrive,label:t('ข้อมูลในเครื่อง','Local data')},{id:'about' as View,icon:CircleHelp,label:t('วิธีการทำงาน','Our approach')}];
 return <div className="app-shell">
 <a className="skip-link" href="#main">{t('ข้ามไปเนื้อหา','Skip to content')}</a>
 {mobile&&<button className="overlay" aria-label={t('ปิดเมนู','Close menu')} onClick={()=>setMobile(false)}/>}
 <aside className={`sidebar ${mobile?'open':''}`}><button className="brand" onClick={()=>navigate('feed')} aria-label="NowInfo"><span className="brand-mark">n</span><span>now<span className="brand-light">info</span><small>BY NOWHEREDEV</small></span></button>
 <div className="nav-label">{t('พื้นที่ของคุณ','YOUR WORKSPACE')}</div><nav>{nav.map(({id,icon:Icon,label})=><button key={id} className={`nav-item ${view===id?'selected':''}`} onClick={()=>navigate(id)}><Icon size={19}/><span>{label}</span>{id==='saved'&&saved.length>0&&<span className="nav-count">{saved.length}</span>}</button>)}</nav>
 <div className="nav-label topics-label">{t('สำรวจตามเรื่อง','EXPLORE TOPICS')}</div><nav>{categories.map(c=>{const Icon=icons[c];return <button key={c} className={`nav-item ${view==='feed'&&category===c?'topic-active':''}`} onClick={()=>selectCategory(c)}><Icon size={18}/><span>{categoryNames[lang][c]}</span></button>;})}</nav>
 <div className="sidebar-bottom"><div className="source-promise"><ShieldCheck size={22}/><strong>{t('ทุกข่าว มีที่มา','Every story has a source')}</strong><p>{t('อ่านต้นทาง เข้าใจบริบท แล้วสร้างมุมมองของคุณเอง','Read the source. Understand the context. Form your own view.')}</p></div><span>NOWINFO <span className="version">v0.2</span></span></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label={t('เปิดเมนู','Open menu')} onClick={()=>setMobile(true)}><Menu size={21}/></button><Globe2 size={17}/><span>{t('แดชบอร์ด','Dashboard')}</span><ChevronRight size={14}/><strong>{t('ศูนย์รวมข่าว','News desk')}</strong></div><div className="topbar-actions"><span className="edition"><HardDrive size={13}/>{t('เก็บข้อมูลในเครื่อง','LOCAL WORKSPACE')}</span><button className="theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={theme==='dark'?t('เปลี่ยนเป็นโหมดสว่าง','Switch to light mode'):t('เปลี่ยนเป็นโหมดมืด','Switch to dark mode')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}<span>{theme==='dark'?'Light':'Dark'}</span></button><button className="language" onClick={()=>setLang(lang==='th'?'en':'th')} aria-label={t('Switch to English','เปลี่ยนเป็นภาษาไทย')}>{lang==='th'?'TH / EN':'EN / TH'}</button></div></header>
 <main id="main"><div className="page-heading"><div><div className="eyebrow"><span className="orange-line"/>GLOBAL NEWS INTELLIGENCE</div><h1>{title}</h1><p>{view==='feed'?t('สำรวจข่าวจากหลายภูมิภาค แล้วเชื่อมโยงเรื่องที่สำคัญกับคุณ','Explore regional perspectives. Connect the stories that matter.'):view==='saved'?t('เก็บไว้ในเบราว์เซอร์นี้ สูงสุด 100 ข่าว','Stored in this browser. Up to 100 stories.'):view==='storage'?t('ข้อมูลอยู่ในเบราว์เซอร์นี้ สำรองและย้ายเครื่องได้ด้วย JSON','Data stays in this browser. Use JSON backups to move between devices.'):view==='sources'?t('ตรวจสอบที่มาและสถานะการดึงข้อมูลล่าสุด','See where the news comes from and when we last checked.'):t('รู้ว่าข้อมูลมาจากไหน และมีข้อจำกัดอะไร','Understand the sources and the limits of the information.')}</p></div><button className="refresh" onClick={refresh} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>{loading?t('กำลังอัปเดต','Updating'):t('อัปเดตข่าว','Refresh feed')}</button></div>
 {storageError&&<p className="notice" role="status">{t('เบราว์เซอร์ไม่อนุญาตให้บันทึกข้อมูล การบันทึกอาจอยู่ได้เฉพาะครั้งนี้','Browser storage is unavailable. Saved items may only last for this session.')}</p>}
 {error&&<p className="notice" role="alert">{t('อัปเดตข่าวไม่สำเร็จ กรุณาลองอีกครั้ง ข้อมูลที่แสดงอาจเป็นข้อมูลจากครั้งก่อน','The update failed. Please retry. Any displayed stories may be from the previous update.')}</p>}
 {cached&&<div className="cache-notice"><HardDrive size={15}/>{t('กำลังแสดงข่าวที่เก็บในเครื่อง','Showing news stored on this device')} · {data?date(data.fetchedAt):''}</div>}
 {data&&data.sources.some(source=>source.status==='unavailable')&&<div className="cache-notice"><Radio size={15}/>{t('บางแหล่งยังไม่พร้อม ข่าวที่เก็บไว้ยังอ่านได้','Some feeds are unavailable. Previously stored stories remain readable.')}<button onClick={()=>navigate('sources')}>{t('ดูสถานะ','View status')}</button></div>}
 {(view==='feed'||view==='saved')&&<>
 <div className="summary-strip"><div><span className="metric-icon"><Radio size={21}/></span><div><span className="metric-label">{t('ข่าวที่เก็บในเครื่อง','STORIES ON DEVICE')}</span><strong>{data?data.articles.length:'—'} <small>{t('ข่าว','stories')}</small></strong></div></div><div><span className="metric-icon"><Globe2 size={21}/></span><div><span className="metric-label">{t('ฟีดที่เชื่อมต่อได้','AVAILABLE FEEDS')}</span><strong>{data?`${sourceCount} / ${data.sources.length}`:'—'} <small>{t('ฟีด','feeds')}</small></strong></div></div><div><span className="metric-icon"><MapPin size={21}/></span><div><span className="metric-label">{t('ภูมิภาคที่พบข่าว','REGIONS IN VIEW')}</span><strong>{data?regions.filter(r=>r!=='global'&&data.articles.some(a=>a.regions.includes(r as Region))).length:'—'} <small>/ 7</small></strong></div></div><div className="updated-metric"><span className="metric-icon"><RefreshCw size={20}/></span><div><span className="metric-label">{t('ดึงข้อมูลล่าสุด · เวลาไทย','LAST FETCH · BANGKOK')}</span><strong className="time-value">{data?date(data.fetchedAt):t('กำลังเชื่อมต่อ','Connecting')}</strong></div></div></div>
 {view==='feed'&&<div className="overview-grid"><WorldMap articles={data?.articles||[]} selected={region} onSelect={setRegion} lang={lang}/><Activity articles={data?.articles||[]} lang={lang} now={now}/></div>}
 <div className="content-grid"><section className="feed-section" aria-label={t('รายการข่าว','News feed')}><div className="section-top"><h2>{view==='saved'?t('รายการอ่านของคุณ','Your saved stories'):t('ข่าวล่าสุด','Latest dispatches')}</h2><span className="muted">{filtered.length} {t('รายการ','results')}</span></div>
 <FocusFilter articles={view==='saved'?saved:data?.articles||[]} value={focus} onChange={setFocus} lang={lang}/><div className="search-row"><label className="searchbox"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('ค้นหาหัวข่าว แหล่งข่าว หรือหมวดหมู่...','Search headlines, sources or topics…')} aria-label={t('ค้นหาข่าว','Search news')}/>{query&&<button className="icon-button" aria-label={t('ล้างคำค้น','Clear search')} onClick={()=>setQuery('')}><X size={15}/></button>}</label></div>
 <div className="category-tabs" aria-label={t('หมวดหมู่ข่าว','News categories')}><button aria-pressed={category==='all'} className={category==='all'?'active':''} onClick={()=>setCategory('all')}>{t('ทั้งหมด','All stories')}</button>{categories.map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c==='world'?t('ข่าวโลก','World'):categoryNames[lang][c]}</button>)}</div>
 <div className="filter-row"><select aria-label={t('ภูมิภาค','Region')} value={region} onChange={e=>setRegion(e.target.value as Region|'all')}><option value="all">{t('ทุกภูมิภาค','All regions')}</option>{regions.map(r=><option key={r} value={r}>{regionNames[lang][r as Region]}</option>)}</select><span><SlidersHorizontal size={14}/>{t('กรองข่าว','Filter')}</span><select aria-label={t('แหล่งข่าว','News source')} value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="all">{t('ทุกแหล่งข่าว','All sources')}</option>{publishers.map(s=><option key={s}>{s}</option>)}</select><select aria-label={t('เรียงข่าว','Sort stories')} value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">{t('ใหม่ที่สุดก่อน','Newest first')}</option><option value="oldest">{t('เก่าที่สุดก่อน','Oldest first')}</option></select></div>
 <div className="articles" aria-live="polite" aria-busy={loading}>
 {loading&&!data&&view!=='saved'?<div className="loading-state"><RefreshCw className="spin" size={26}/><h3>{t('กำลังรวบรวมข่าวจากต้นทาง','Connecting to the sources')}</h3><p>{t('รอสักครู่ ข่าวพร้อมแหล่งอ้างอิงกำลังมา','Headlines and their source links will appear here shortly.')}</p></div>:filtered.length===0?<div className="empty-state"><Search size={30}/><h3>{view==='saved'&&!saved.length?t('ยังไม่มีข่าวที่บันทึก','No saved stories yet'):t('ยังไม่พบข่าวในรายการนี้','No stories found')}</h3><p>{view==='saved'&&!saved.length?t('กดสัญลักษณ์บันทึกบนข่าวที่ต้องการกลับมาอ่าน','Use the bookmark button on a story to save it here.'):t('ลองเปลี่ยนคำค้น หมวดหมู่ หรืออัปเดตข้อมูลอีกครั้ง','Try another search, change the filters or refresh the feed.')}</p><button className="text-button" onClick={view==='saved'&&!saved.length?()=>navigate('feed'):clearFilters}>{t('ดูข่าวทั้งหมด','Browse all stories')} <ChevronRight size={15}/></button></div>:filtered.slice(0,limit).map((a,i)=>{const Icon=icons[a.category];return <article key={a.id} className={`news-card ${i===0&&view==='feed'?'lead-card':''}`}><div className="article-body"><div className="article-meta"><span className={`category-tag ${a.category}`}><Icon size={13}/>{categoryNames[lang][a.category]}</span>{i===0&&view==='feed'&&sort==='newest'&&<span className="latest-tag">{t('ล่าสุดในรายการ','LATEST IN VIEW')}</span>}</div><button className="headline" onClick={()=>setActive(a)}>{a.title}</button><div className="headline-evidence">{focusEvidence(a).slice(0,2).map(e=><span key={e.id} title={e.terms.join(", ")}>{focusTopics.find(topic=>topic.id===e.id)?.[lang]} · {e.terms.slice(0,2).join(", ")}</span>)}</div><div className="article-footer"><span className="publisher-mark">{a.source.slice(0,1)}</span><span className="source-name">{a.source}</span><span className="article-region"><MapPin size={12}/>{a.regions.slice(0,2).map(r=>regionNames[lang][r]).join(' · ')}</span><span className="separator">/</span><time dateTime={a.publishedAt||undefined}>{date(a.publishedAt)}</time></div><button className="context-link" onClick={()=>setActive(a)}>{t('เปิดประเด็นที่ควรติดตาม','Explore the context')} <ArrowUpRight size={15}/></button></div><button className={`bookmark ${isSaved(a)?'bookmarked':''}`} onClick={()=>bookmark(a)} aria-label={isSaved(a)?t('นำออกจากที่บันทึก','Remove saved story'):t('บันทึกข่าว','Save story')} aria-pressed={isSaved(a)}><Bookmark size={19} fill={isSaved(a)?'currentColor':'none'}/></button></article>;})}
 </div>{filtered.length>limit&&<button className="load-more" onClick={()=>setLimit(limit+24)}>{t('ดูข่าวเพิ่มเติม','Load more stories')} <ChevronRight size={16}/></button>}</section>
 <aside className="insights"><section className="focus-panel"><div className="eyebrow"><Sparkles size={15}/> A WIDER PERSPECTIVE</div><h2>{t('อ่านให้ไกลกว่า','Go beyond')}<br/><span>{t('พาดหัวข่าว','the headline.')}</span></h2><p>{t('ข่าวหนึ่งเรื่องอาจเชื่อมโยงหลายมิติ เริ่มจากคำถามที่ใช่','One story can connect many parts of the world. Start with the right questions.')}</p><ol><li><span>01</span><div><strong>{t('เกิดอะไรขึ้น','What happened?')}</strong><small>{t('ตรวจสอบข้อเท็จจริงจากต้นทาง','Check the original reporting')}</small></div></li><li><span>02</span><div><strong>{t('เกี่ยวข้องกับใคร','Who is affected?')}</strong><small>{t('มองคน พื้นที่ และภาคธุรกิจ','Look at people, places and sectors')}</small></div></li><li><span>03</span><div><strong>{t('ติดตามอะไรต่อ','What comes next?')}</strong><small>{t('แยกสิ่งที่ยืนยันแล้วกับสิ่งที่ต้องรอดู','Separate evidence from open questions')}</small></div></li></ol></section>
 <section className="topic-panel"><div className="section-top"><h3>{t('ภาพรวมหมวดข่าว','Topic overview')}</h3><BarChart3 size={17}/></div><p>{t('จำนวนข่าวในฟีด ไม่ใช่ระดับความเสี่ยง','Feed volume, not a measure of risk')}</p>{categories.map(c=>{const count=data?.articles.filter(a=>a.category===c).length||0;return <button className="topic-stat" key={c} onClick={()=>selectCategory(c)}><span>{categoryNames[lang][c]}<b>{count}</b></span><span className="bar"><i style={{width:`${count/Math.max(data?.articles.length||0,1)*100}%`}}/></span></button>;})}</section>
 <section className="transparency-note"><ShieldCheck size={18}/><p>{t('หัวข่าวแสดงภาษาต้นฉบับ หมวดหมู่จัดด้วยกฎคำสำคัญและอาจคลาดเคลื่อน','Headlines retain their original language. Keyword-based categories can be imperfect.')} <button onClick={()=>navigate('about')}>{t('อ่านวิธีการทำงาน','How it works')} <ArrowUpRight size={13}/></button></p></section></aside></div></>}
 {view==='sources'&&<div className="sources-grid">{(data?.sources||[]).map(s=><section className="source-card" key={s.id}><div className="section-top"><Radio size={22}/><span className={`status-pill ${s.status==='ok'?'ok':''}`}>{s.status==='ok'?t('เชื่อมต่อได้','Available'):t('ไม่พร้อมใช้งาน','Unavailable')}</span></div><h2>{s.name}</h2><p>{categoryNames[lang][s.category]} · {regionNames[lang][s.region]}</p><dl><div><dt>{t('หัวข่าวที่อ่านได้ก่อนรวมซ้ำ','Headlines before deduplication')}</dt><dd>{s.count}</dd></div><div><dt>{t('ตรวจสอบล่าสุด · เวลาไทย','Last checked · Bangkok')}</dt><dd>{date(s.checkedAt)}</dd></div></dl><a href={s.site} target="_blank" rel="noopener noreferrer">{t('เปิดเว็บไซต์ต้นทาง','Visit the source')}<ExternalLink size={16}/></a></section>)}{!data&&<p>{loading?t('กำลังตรวจสอบแหล่งข้อมูล…','Checking sources…'):t('ยังโหลดแหล่งข้อมูลไม่ได้ กรุณาอัปเดตอีกครั้ง','Sources could not be loaded. Please refresh.')}</p>}</div>}
 {view==='storage'&&<section className="storage-panel panel"><HardDrive size={32}/><h2>{t('พื้นที่ข่าวส่วนตัว บนอุปกรณ์ของคุณ','Your news. Your device.')}</h2><p>{t('เก็บข่าวล่าสุดสูงสุด 500 รายการในช่วง 7 วัน พร้อมข่าวบันทึก 100 รายการ แคชเก่าอาจถูกลดจำนวนเมื่อพื้นที่ไม่พอ ข่าวบันทึกจะไม่ถูกลบเพื่อเพิ่มพื้นที่แคช','Store up to 500 headlines from the past 7 days, plus 100 saved stories. The cache shrinks if storage is full. Saved stories are never deleted to make room for cached news.')}</p><div className="storage-stats"><div><strong>{data?.articles.length||0}</strong><span>{t('ข่าวในเครื่อง','Cached stories')}</span></div><div><strong>{saved.length}</strong><span>{t('ข่าวบันทึก','Saved stories')}</span></div><div><strong>{theme==='dark'?'Dark':'Light'}</strong><span>{t('โหมดที่เลือก','Selected theme')}</span></div></div><div className="dialog-actions"><button className="primary-button" onClick={exportData}><Download size={17}/>{t('ส่งออกข้อมูล JSON','Export JSON backup')}</button><button className="refresh" onClick={()=>importInput.current?.click()}><Upload size={17}/>{t('นำเข้าไฟล์สำรอง','Import backup')}</button><input ref={importInput} type="file" accept="application/json,.json" hidden onChange={e=>importData(e.target.files?.[0])}/></div>{message&&<p className="notice" role="status">{message}</p>}<p className="storage-footnote">{t('การล้างข้อมูลเว็บไซต์อาจลบรายการเหล่านี้ สำรองข้อมูลก่อนย้ายเครื่อง ส่วนการดึงข่าวใหม่ต้องเชื่อมต่ออินเทอร์เน็ต','Clearing site data may remove these items. Export a backup before switching devices. Fetching new stories requires an internet connection.')}</p></section>}
 {view==='about'&&<div className="about-content"><section><ShieldCheck size={30}/><h2>{t('ที่มาชัดเจน มุมมองเป็นของคุณ','Transparent sources. Your own perspective.')}</h2><p>{t('NowInfo เป็นตัวรวบรวมหัวข่าวและลิงก์จาก RSS ของ BBC News, DW, France 24, Al Jazeera, CNA, Federal Reserve และ UN News ไม่ได้เป็นผู้รายงานข่าวต้นฉบับ เปิดลิงก์ต้นทางเพื่ออ่านเนื้อหาเต็มและบริบท','NowInfo brings together RSS headlines and links from BBC News, DW, France 24, Al Jazeera, CNA, the Federal Reserve and UN News. We do not produce the original reporting. Follow the source link for the full story and context.')}</p></section><section><h3>{t('ข้อมูลใหม่แค่ไหน','How fresh is the feed?')}</h3><p>{t('ตรวจสอบข้อมูลทุก 5 นาทีขณะเปิดหน้าเว็บ และแคชผลการดึงข้อมูลประมาณ 5 นาที เวลาเผยแพร่ยึดตามแหล่งข่าว ส่วนเวลาดึงข้อมูลคือเวลาที่ระบบอ่าน RSS หากแหล่งข่าวไม่ตอบสนองจะแสดงสถานะไม่พร้อมใช้งาน ไม่มีการเติมข่าวจำลอง','While the page is visible, the feed is checked every 5 minutes. Responses are cached for about 5 minutes. Publication times come from the publisher; the fetch time is when RSS was retrieved. Unresponsive sources are marked unavailable. No simulated headlines are inserted.')}</p></section><section><h3>{t('หมวดหมู่และประเด็นติดตาม','Categories and context prompts')}</h3><p>{t('หมวดหมู่มาจากฟีดและคำสำคัญในหัวข่าว จึงอาจจัดผิดได้ คำถามประกอบข่าวเป็นกรอบคิดทั่วไปตามหมวด ไม่ใช่ผลวิเคราะห์เฉพาะข่าว ไม่มีการให้คะแนนผลกระทบ ความเชื่อมั่น หรือคาดการณ์ราคาสินทรัพย์','Categories use the feed topic and headline keywords and can be incorrect. Context questions are general prompts by category, not analysis of the individual story. We do not assign impact or confidence scores or forecast asset prices.')}</p></section><section><h3>{t('ความครอบคลุมและการเก็บข้อมูล','Coverage and storage')}</h3><p>{t('ฟีดครอบคลุมหลายภูมิภาคแต่ยังใช้ภาษาอังกฤษเป็นหลัก ไม่ครอบคลุมทุกประเทศหรือทุกมุมมอง พื้นที่ข่าวอิงหมวดฟีดและคำสำคัญในหัวข่าว จึงอาจคลาดเคลื่อน แผนที่ไม่ได้ระบุตำแหน่งเกิดเหตุ ข่าวแคชเก็บสูงสุด 500 รายการในช่วง 7 วัน ข่าวบันทึกสูงสุด 100 รายการแยกจากแคช ธีม ภาษา และตัวกรองเก็บใน localStorage ไม่ซิงก์ข้ามเครื่อง','Feeds cover multiple regions, primarily in English, not every country or perspective. Regions are inferred from feed scope and headline keywords and can be imperfect; map markers are not event locations. Up to 500 recent headlines are cached for 7 days. Up to 100 bookmarks are kept separately. Theme, language and filters stay in localStorage and do not sync across devices.')}</p></section></div>}
 <footer><span>© {new Date().getFullYear()} NOWHEREDEV <span className="footer-divider">/</span> nowinfo</span><span>{t('อ่านโลก ด้วยความเข้าใจ','Read the world with context')} <Globe2 size={14}/></span></footer></main></div>
 <dialog ref={dialog} className="story-dialog" aria-labelledby="story-title" onClose={()=>setActive(null)} onClick={e=>{if(e.target===dialog.current)dialog.current.close();}}>{active&&<div className="dialog-content"><div className="section-top"><span className={`category-tag ${active.category}`}>{categoryNames[lang][active.category]}</span><button className="icon-button" aria-label={t('ปิดรายละเอียด','Close details')} onClick={()=>dialog.current?.close()}><X size={23}/></button></div><h2 id="story-title">{active.title}</h2><p className="dialog-meta">{active.source} · {date(active.publishedAt)} · {t('เวลาไทย','Bangkok')}</p><div className="context-box"><div className="eyebrow"><Sparkles size={16}/>{t('ประเด็นที่ควรติดตาม','QUESTIONS TO EXPLORE')}</div><p>{t('กรอบคิดทั่วไปตามหมวดข่าว ไม่ใช่ข้อสรุปเกี่ยวกับข่าวนี้','General questions for this topic, not conclusions about this story.')}</p><ul>{context[active.category][lang].map(q=><li key={q}>{q}</li>)}</ul></div><div className="dialog-actions"><a className="primary-button" href={active.url} target="_blank" rel="noopener noreferrer">{t('อ่านข่าวจากต้นทาง','Read original story')}<ArrowUpRight size={18}/></a><button className="refresh" onClick={()=>bookmark(active)}>{isSaved(active)?<Check size={17}/>:<Bookmark size={17}/>} {isSaved(active)?t('บันทึกแล้ว','Saved'):t('บันทึกไว้อ่าน','Save story')}</button></div></div>}</dialog>
 </div>;
}
