'use client';
import {useMemo,useState} from 'react';
import {ArrowUpRight,Bookmark,Layers3,Search,Bell,Check,X} from 'lucide-react';
import type {Article,NewsEvent,Interests,ReadingRecord,TrackedEvent} from '@/lib/types';
import {clusterEvents} from '@/lib/events.mjs';
import {focusTopics,matchesFocus} from '@/lib/focus.mjs';
import {regionNames,regions} from '@/lib/regions.mjs';
import FocusFilter from './focus-filter';
import TranslatedHeadline from './translated-headline';
import InterestsEditor from './interests-editor';
import {hasInterests,interestMatches,isTrackedEvent,articleState} from '@/lib/workspace.mjs';
import {countryOptions,thailandEvidence} from '@/lib/focus.mjs';
import {matchesThailandLens,thailandLenses} from '@/lib/thailand.mjs';

type Props={history:ReadingRecord[];trackedEvents:TrackedEvent[];baseline:number;onRead:(article:Article,read:boolean)=>void;onTrack:(event:NewsEvent)=>void;onUnfollow:(id:string)=>void;mode:'events'|'following'|'thailand';interests:Interests;onInterests:(value:Interests)=>void;articles:Article[];lang:'th'|'en';loading:boolean;saved:Article[];onBookmark:(article:Article)=>void;onOpen:(article:Article)=>void};
export default function EventDesk({articles,lang,loading,saved,onBookmark,onOpen,mode,interests,onInterests,history,trackedEvents,baseline,onRead,onTrack,onUnfollow}:Props) {
  const [focus,setFocus]=useState(mode==='events'?'relevant':'all');
  const [lens,setLens]=useState('direct');
  const [reading,setReading]=useState('all');
  const state=(article:Article)=>articleState(article,history,baseline);
  const [region,setRegion]=useState('all');
  const [query,setQuery]=useState('');
  const [limit,setLimit]=useState(18);
  const t=(th:string,en:string)=>lang==='th'?th:en;
  const events=useMemo(()=>clusterEvents(articles) as NewsEvent[],[articles]);
  const filtered=useMemo(()=>events.filter(event=>(mode!=='thailand'||event.articles.some(article=>matchesThailandLens(article,lens)))&&(mode!=='following'||isTrackedEvent(event,trackedEvents)||event.articles.some(article=>interestMatches(article,interests).matched))&&(reading==='all'||event.articles.some(article=>reading==='new'?articleState(article,history,baseline).isNew:!articleState(article,history,baseline).read))&&event.articles.some(article=>matchesFocus(article,focus))&&(region==='all'||event.regions.includes(region))&&event.articles.some(article=>`${article.title} ${article.source}`.toLowerCase().includes(query.trim().toLowerCase()))),[events,focus,region,query,mode,interests,reading,history,baseline,trackedEvents,lens]);
  const date=(value:string|null)=>value?new Intl.DateTimeFormat(lang==='th'?'th-TH':'en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Bangkok'}).format(new Date(value)):t('ไม่ระบุเวลา','Time unavailable');
  return <section className="event-desk" aria-label={t('เหตุการณ์สำคัญ','Event desk')}>
    {mode==='following'&&<><InterestsEditor value={interests} onChange={onInterests} lang={lang}/>{trackedEvents.length>0&&<section className="tracked-list panel"><h3>{t('เหตุการณ์ที่ติดตาม','Followed stories')} · {trackedEvents.length}/30</h3><ul>{trackedEvents.map(item=><li key={item.id}><div><TranslatedHeadline title={item.title} lang={lang}/>{!events.some(event=>event.articles.some(article=>item.urls.includes(article.url)))&&<small>{t('ไม่มีบทความของเหตุการณ์นี้ในแคชปัจจุบัน','No articles from this story in the current cache')}</small>}</div><button className="icon-button" aria-label={t('เลิกติดตาม: ','Unfollow: ')+item.title} onClick={()=>onUnfollow(item.id)}><X size={17}/></button></li>)}</ul></section>}</>}
    <div className="event-intro panel"><div><Layers3 size={23}/><h2>{t('หลายแหล่งข่าว เรื่องเดียวกัน','More sources. One story.')}</h2></div><p>{t('จัดกลุ่มจากคำในหัวข่าวและเวลาเผยแพร่ภายใน 72 ชั่วโมง ชื่อกลุ่มใช้หัวข่าวล่าสุด ไม่มีการสร้างข้อสรุปแทนสำนักข่าว','Grouped by headline similarity within 72 hours. Each group uses its latest headline, without generating a new factual summary.')}</p><span>{t('การจัดกลุ่มอัตโนมัติอาจคลาดเคลื่อน หลายสำนักข่าวอาจใช้รายงานต้นทางเดียวกัน','Automatic grouping can be imperfect. Different publishers may share the same original reporting.')}</span></div>
    {mode==='thailand'&&<section className="thailand-panel panel"><div className="focus-options" aria-label={t('มุมมองไทย','Thailand lens')}>{thailandLenses.map(item=><button key={item.id} aria-pressed={lens===item.id} onClick={()=>{setLens(item.id);setFocus('all');setRegion('all');setQuery('');setReading('all');setLimit(18);}}>{item[lang]}</button>)}</div><p>{thailandLenses.find(item=>item.id===lens)?.question[lang]}</p>{lens!=='direct'&&<span>{t('เป็นคำถามเพื่อติดตามข่าวโลก ยังไม่ได้ยืนยันผลกระทบต่อไทย','These are questions for following global news, not confirmed effects on Thailand.')}</span>}</section>}
    <FocusFilter articles={articles} value={focus} onChange={value=>{setFocus(value);setLimit(18);}} lang={lang}/>
    <div className="event-controls"><label className="searchbox"><Search size={18}/><input aria-label={t('ค้นหาเหตุการณ์','Search events')} placeholder={t('ค้นหาเหตุการณ์หรือสำนักข่าว','Search headlines or publishers')} value={query} onChange={e=>{setQuery(e.target.value);setLimit(18);}}/></label><select aria-label={t('ภูมิภาคของเหตุการณ์','Event region')} value={region} onChange={e=>{setRegion(e.target.value);setLimit(18);}}><option value="all">{t('ทุกภูมิภาค','All regions')}</option>{regions.map(r=><option value={r} key={r}>{regionNames[lang][r as keyof typeof regionNames.th]}</option>)}</select><select aria-label={t('สถานะการอ่าน','Reading status')} value={reading} onChange={e=>{setReading(e.target.value);setLimit(18);}}><option value="all">{t('ทุกสถานะ','Any status')}</option><option value="unread">{t('มีข่าวที่ยังไม่อ่าน','Has unread articles')}</option><option value="new">{t('มีข่าวใหม่ในเครื่องนี้','New on this device')}</option></select></div>
    <div className="section-top event-result-count"><h2>{t('เหตุการณ์ที่พบ','Matching stories')}</h2><span>{filtered.length} {t('กลุ่ม','groups')} · {filtered.reduce((sum,event)=>sum+event.articles.length,0)} {t('บทความ','articles')}</span></div>
    {!filtered.length?<div className="empty-state"><h3>{loading&&!articles.length?t('กำลังรวบรวมข่าว','Gathering headlines'):mode==='following'&&!hasInterests(interests)&&!trackedEvents.length?t('เริ่มจากเลือกเรื่องที่สนใจด้านบน','Choose an interest above to get started'):t('ยังไม่พบเหตุการณ์ตามตัวกรอง','No matching stories')}</h3><p>{t('ลองเปลี่ยนประเด็น ภูมิภาค หรือคำค้น','Try another topic, region or search.')}</p><button className="text-button" onClick={()=>{setFocus('all');setRegion('all');setQuery('');setReading('all');}}>{t('ดูข่าวทั้งหมด','Show all headlines')}</button></div>:<div className="event-grid">{filtered.slice(0,limit).map(event=><article className="event-card panel" key={event.id}>
      <div className="event-card-top"><span>{event.publishers.length} {t('สำนักข่าว','publishers')} · {event.articles.length} {t('บทความ','articles')}</span><time>{date(event.latestAt)}</time></div>
      <div className="event-reading"><span>{event.articles.filter(article=>!state(article).read).length} {t('ยังไม่อ่าน','unread')}</span>{event.articles.some(article=>state(article).isNew)&&<span className="new-label">{event.articles.filter(article=>state(article).isNew).length} {t('ข่าวใหม่ในเครื่องนี้','new on this device')}</span>}<button aria-pressed={isTrackedEvent(event,trackedEvents)} disabled={!isTrackedEvent(event,trackedEvents)&&trackedEvents.length>=30} title={t('ติดตามได้สูงสุด 30 เหตุการณ์','Follow up to 30 stories')} onClick={()=>onTrack(event)}><Bell size={15}/>{isTrackedEvent(event,trackedEvents)?t('กำลังติดตาม','Following'):t('ติดตามเหตุการณ์','Follow story')}</button></div>
      <TranslatedHeadline title={event.title} lang={lang} as="button" className="event-title" onClick={()=>onOpen(event.articles[0])}/>
      {mode==='thailand'&&lens==='direct'&&<p className="match-reason">{t('คำที่กล่าวถึงไทย','Thailand mention')}: {[...new Set(event.articles.flatMap(article=>thailandEvidence(article)))].join(', ')}</p>}
      <div className="event-tags">{event.topics.map(id=><span key={id}>{focusTopics.find(topic=>topic.id===id)?.[lang]}</span>)}</div>
      {mode==='following'&&<p className="match-reason">{isTrackedEvent(event,trackedEvents)?t('คุณติดตามเหตุการณ์นี้','You follow this story'):t('ตรงกับที่คุณติดตาม','Matches your interests')}: {[...new Set(event.articles.flatMap(article=>{const match=interestMatches(article,interests);return [...match.keywords,...match.topics.map(id=>focusTopics.find(topic=>topic.id===id)?.[lang]),...match.countries.map(id=>countryOptions.find(country=>country.id===id)?.[lang])];}))].join(', ')}</p>}
      <p className="event-publishers">{event.publishers.join(' / ')}</p>
      {event.articles.length>1&&<p className="group-reason">{t('คำร่วมในหัวข่าว','Shared headline words')}: {event.sharedTerms.join(', ')}</p>}
      <details className="event-timeline"><summary>{t('ดูแหล่งข่าวและลำดับเวลา','Sources & timeline')} <ArrowUpRight size={15}/></summary><ol>{[...event.articles].reverse().map(article=><li key={article.url}><div><time>{date(article.publishedAt)} · {t('เวลาไทย','Bangkok')}</time><TranslatedHeadline title={article.title} lang={lang} as="a" href={article.url} onClick={()=>onRead(article,true)}/><span>{article.source}</span><button className="mark-read" onClick={()=>onRead(article,!state(article).read)}>{state(article).read?<Check size={14}/>:null}{state(article).read?t('อ่านแล้ว · ทำเป็นยังไม่อ่าน','Read · Mark unread'):t('ทำเครื่องหมายว่าอ่านแล้ว','Mark read')}</button></div><button className={`bookmark ${saved.some(item=>item.url===article.url)?'bookmarked':''}`} aria-label={t('บันทึกบทความ: ','Save article: ')+article.title} aria-pressed={saved.some(item=>item.url===article.url)} onClick={()=>onBookmark(article)}><Bookmark size={17}/></button></li>)}</ol></details>
    </article>)}</div>}
    {filtered.length>limit&&<button className="load-more" onClick={()=>setLimit(limit+18)}>{t('ดูเหตุการณ์เพิ่มเติม','Load more stories')}</button>}
  </section>;
}
