'use client';
import {Globe2,MoveUpRight} from 'lucide-react';
import geography from '@/lib/world-map.json';
import {regionNames,regions} from '@/lib/regions.mjs';
import type {Article,Region} from '@/lib/types';
export default function WorldMap({articles,selected,onSelect,lang}:{articles:Article[];selected:Region|'all';onSelect:(r:Region|'all')=>void;lang:'th'|'en'}){
 const counts=Object.fromEntries(regions.map(r=>[r,articles.filter(a=>a.regions.includes(r as Region)).length]));
 return <section className="world-panel panel" aria-label={lang==='th'?'แผนที่เลือกภูมิภาค':'Regional news map'}><div className="panel-heading"><div><span className="eyebrow">GLOBAL COVERAGE</span><h2>{lang==='th'?'มองข่าวรอบโลก':'Your world, in focus'}</h2></div><button className="map-reset" onClick={()=>onSelect('all')}><Globe2 size={15}/>{lang==='th'?'ทุกภูมิภาค':'All regions'}</button></div><div className="map-wrap"><svg viewBox="0 0 800 365" aria-label={lang==='th'?'แผนที่โลก แสดงจำนวนข่าวตามภูมิภาค':'World map with regional news counts'}><path d={geography.grid} className="map-grid"/><path d={geography.land} className="map-land"/>{Object.entries(geography.centers).map(([key,[x,y]])=>{const r=key as Region;const count=counts[r]||0;return <g key={r} className={`map-point ${selected===r?'chosen':''} ${count?'has-news':''}`} role="button" tabIndex={0} aria-label={`${regionNames[lang][r]} ${count}`} aria-pressed={selected===r} onClick={()=>onSelect(selected===r?'all':r)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(selected===r?'all':r);}}}><title>{regionNames[lang][r]} · {count}</title><circle cx={x} cy={y} r={20} className="point-halo"/><circle cx={x} cy={y} r={7} className="point-core"/><rect x={x-20} y={y+13} width={40} height={22} rx={6} className="map-count-bg"/><text x={x} y={y+29} textAnchor="middle">{count}</text></g>;})}</svg><div className="map-caption"><span className="map-dot"/>{lang==='th'?'เลือกภูมิภาคเพื่อกรองข่าว':'Select a region to filter stories'}<MoveUpRight size={13}/></div></div><div className="region-pills">{regions.map(key=>{const r=key as Region;return <button key={r} className={selected===r?'active':''} aria-pressed={selected===r} onClick={()=>onSelect(selected===r?'all':r)}>{regionNames[lang][r]}<span>{counts[r]||0}</span></button>;})}</div><p className="map-footnote">{lang==='th'?'หมุดแทนภูมิภาค ไม่ใช่จุดเกิดเหตุ • ข่าวหนึ่งเรื่องอาจอยู่ได้หลายภูมิภาค':'Markers represent regions, not event locations. A story can span multiple regions.'}</p></section>;
}
