import type {Category} from './types';
export const categories:Category[]=['world','economy','technology','energy','climate'];
export const categoryNames={th:{world:'โลกและภูมิรัฐศาสตร์',economy:'เศรษฐกิจ',technology:'เทคโนโลยี',energy:'พลังงาน',climate:'สิ่งแวดล้อม'},en:{world:'World & geopolitics',economy:'Economy',technology:'Technology',energy:'Energy',climate:'Environment'}};
export const context:Record<Category,{th:string[];en:string[]}>= {
 world:{th:['เหตุการณ์นี้เปลี่ยนความสัมพันธ์ระหว่างประเทศอย่างไร?','มีผลต่อเส้นทางการค้า ความปลอดภัย หรือการเดินทางหรือไม่?','มีคำยืนยันจากหน่วยงานหรือแหล่งข่าวอื่นแล้วหรือยัง?'],en:['Does this change international relations?','Could trade routes, safety or travel be affected?','Have other sources or authorities confirmed the report?']},
 economy:{th:['ประกาศนี้เกี่ยวข้องกับดอกเบี้ย เงินเฟ้อ หรือการจ้างงานหรือไม่?','ครัวเรือนและธุรกิจกลุ่มใดอาจได้รับผลกระทบ?','ต้องรอดูข้อมูลหรือประกาศอย่างเป็นทางการอะไรต่อ?'],en:['Does this involve interest rates, inflation or employment?','Which households or businesses could be affected?','Which data release or official statement should be watched next?']},
 technology:{th:['เทคโนโลยีนี้อยู่ในขั้นวิจัย ทดลอง หรือใช้งานจริง?','มีผลต่องาน ข้อมูลส่วนบุคคล หรือการแข่งขันอย่างไร?','หลักฐานด้านประสิทธิภาพและข้อจำกัดมีอะไรบ้าง?'],en:['Is this research, a pilot or a deployed technology?','How could jobs, privacy or competition be affected?','What evidence supports performance claims and limitations?']},
 energy:{th:['มีการเปลี่ยนแปลงด้านอุปทาน อุปสงค์ หรือเส้นทางขนส่งหรือไม่?','ต้นทุนของผู้ใช้พลังงานกลุ่มใดอาจเปลี่ยนแปลง?','ต้องติดตามข้อมูลปริมาณผลิตและนโยบายใดต่อ?'],en:['Are supply, demand or transport routes changing?','Which energy users could see a change in costs?','Which production data or policy decisions should be watched?']},
 climate:{th:['พื้นที่และประชากรกลุ่มใดเกี่ยวข้องกับเหตุการณ์?','มีข้อมูลจากหน่วยงานวิทยาศาสตร์หรือประกาศเตือนหรือไม่?','ผลต่ออาหาร น้ำ การเดินทาง และโครงสร้างพื้นฐานคืออะไร?'],en:['Which places and populations are involved?','Is scientific evidence or an official alert available?','What could this mean for food, water, travel and infrastructure?']}
};
